# Generated by Django 3.2 on 2021-04-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerregistration',
            name='date',
        ),
        migrations.AddField(
            model_name='volunteerregistration',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='volunteerregistration',
            name='whatsapp',
            field=models.CharField(max_length=12),
        ),
    ]
