# Generated by Django 3.2 on 2021-04-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0002_auto_20210426_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerregistration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
