# Generated by Django 3.2 on 2021-04-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0004_alter_volunteerregistration_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerRegistration',
            new_name='VolunteerModel',
        ),
        migrations.AlterModelOptions(
            name='volunteermodel',
            options={},
        ),
    ]
