# Generated by Django 3.2 on 2021-04-27 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0005_auto_20210427_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='preferred_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10), blank=True, null=True, size=None),
        ),
    ]
