# Generated by Django 3.2 on 2021-04-27 16:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0006_auto_20210427_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteermodel',
            old_name='created_date',
            new_name='joined_date',
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='discord_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='preferred_timings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('7AM-10AM', '7AM-10AM'), ('10AM-1PM', '10AM-1PM'), ('1PM-4PM', '1PM-4PM'), ('4PM-7PM', '4PM-7PM'), ('7PM-9PM', '7PM-9PM'), ('9PM-11PM', '9PM-11PM'), ('11PM-1AM', '11PM-1AM'), ('1AM-3AM', '1AM-3AM'), ('3AM-5AM', '3AM-5AM'), ('5AM-7AM', '5AM-7AM')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='preferred_volountary_work',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VERIFICATION', 'VERIFICATION'), ('COLLATE', 'COLLATE'), ('SOS-HELP', 'SOS-HELP')], max_length=20), null=True, size=None),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='social_media',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='preferred_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
