# Generated by Django 3.2 on 2021-04-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0007_auto_20210427_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteermodel',
            old_name='preferred_volountary_work',
            new_name='preferred_work',
        ),
    ]
