# Generated by Django 3.2 on 2021-04-28 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0010_volunteermodel_specific_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermodel',
            name='preferred_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='preferred_timings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('7AM-10AM', '7AM-10AM'), ('10AM-1PM', '10AM-1PM'), ('1PM-4PM', '1PM-4PM'), ('4PM-7PM', '4PM-7PM'), ('7PM-9PM', '7PM-9PM'), ('9PM-11PM', '9PM-11PM'), ('11PM-1AM', '11PM-1AM'), ('1AM-3AM', '1AM-3AM'), ('3AM-5AM', '3AM-5AM'), ('5AM-7AM', '5AM-7AM')], max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='specific_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
