# Generated by Django 3.2 on 2021-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0012_alter_volunteermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermodel',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
