# Generated by Django 3.2 on 2021-05-01 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0013_alter_volunteermodel_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermodel',
            name='social_media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254, null=True), null=True, size=None),
        ),
    ]
