# Generated by Django 3.2 on 2021-05-01 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0014_alter_volunteermodel_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermodel',
            name='social_media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), null=True, size=None),
        ),
    ]
